- name: Create nexus service user
  user:
    name: nexus
    home: /opt/nexus
  become: yes

- name: Check if nexus is installed and running 
  command: systemctl status nexus
  register: nexus_status
  failed_when: nexus_status.rc != 0
  ignore_errors: yes

- name: Download nexus
  when: nexus_status|failed
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /tmp
  become: yes
  become_user: nexus

- name: Unpack nexus
  when: nexus_status|failed
  unarchive:
    src: /tmp/nexus-3.7.1-02-unix.tar.gz
    dest: /opt/nexus
    remote_src: yes
  become: yes
  become_user: nexus

- name: Install nexus
  when: nexus_status|failed
  shell: /opt/nexus/nexus-3.7.1-02/bin/nexus run &> nexus.out
  become: yes
  become_user: nexus
  async: 120
  poll: 0

- name: Wait for nexus to install
  when: nexus_status|failed
  wait_for:
    port: 8081
    state: started
  become: yes
    

- name: Set nexus user to run nexus service
  when: nexus_status|failed
  lineinfile:
    path: /opt/nexus/nexus-3.7.1-02/bin/nexus.rc
    state: present
    line: run_as_user="nexus"
  become: yes

- name: Provide systemd nexus service 
  when: nexus_status|failed
  template:
    src: nexus.service.j2
    dest: /usr/lib/systemd/system/nexus.service
    owner: root
    mode: 0644
  become: yes

- name: Restart and enable nexus
  when: nexus_status|failed
  service: 
    name: nexus
    state: restarted 
    enabled: yes
  become: yes
